
import { BookingType, TeeTime } from './types';

export const REGIONS = [
  { id: 'ALL', label: '전체' },
  { id: 'SUDOKWON_SOUTH', label: '수도권 남부' },
  { id: 'SUDOKWON_NORTH', label: '수도권 북부' },
  { id: 'CHUNGCHEONG', label: '충청' },
  { id: 'GANGWON', label: '강원' },
  { id: 'THAILAND', label: '태국' },
  { id: 'CHINA', label: '중국' },
  { id: 'JAPAN', label: '일본' },
  { id: 'VIETNAM', label: '베트남' },
];

export const MOCK_TEE_TIMES: TeeTime[] = [
  {
    id: 't1',
    course: {
      id: 'c5',
      name: '하이난 미션힐스',
      location: '중국 하이커우',
      region: 'CHINA',
      image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=1600&auto=format&fit=crop',
    },
    date: '2024-10-24',
    time: 'SHOTGUN',
    price: 899000,
    originalPrice: 1200000,
    slotsTotal: 72,
    slotsRemaining: 15,
    type: BookingType.FESTA,
    manager: {
      id: 'm5',
      name: '골프몬투어',
      rating: 5.0,
      reviewCount: 5000,
      isVerified: true,
    },
    description: '[ALL포함 단독행사] 72인 샷건 티오프 페스타! 3박 4일 풀패키지.',
  },
  {
    id: 't2',
    course: {
      id: 'c6',
      name: '하이난 미란/고염전 CC',
      location: '중국 하이난',
      region: 'CHINA',
      image: 'https://images.unsplash.com/photo-1592919016386-3e0f5c09756b?q=80&w=1600&auto=format&fit=crop',
    },
    date: '2024-11-15',
    time: '08:00',
    price: 1099000,
    originalPrice: 1500000,
    slotsTotal: 40,
    slotsRemaining: 8,
    type: BookingType.TOUR,
    manager: {
      id: 'm1',
      name: '김프로',
      rating: 4.9,
      reviewCount: 1250,
      isVerified: true,
    },
    description: '[11월 정기 월례회] 가을의 끝 무렵, 하이난 2색 골프 3박 4일.',
  },
  {
    id: 't3',
    course: {
      id: 'c7',
      name: '토조노모리CC',
      location: '일본 오사카',
      region: 'JAPAN',
      image: 'https://images.unsplash.com/photo-1600585154340-be6199f7e009?q=80&w=1600&auto=format&fit=crop',
    },
    date: '2024-08-15',
    time: '09:00',
    price: 1250000,
    originalPrice: 1600000,
    slotsTotal: 20,
    slotsRemaining: 4,
    type: BookingType.TOUR,
    manager: {
      id: 'm2',
      name: '이지혜 매니저',
      rating: 4.8,
      reviewCount: 3400,
      isVerified: true,
    },
    description: '명문 3색 골프!! 여름휴가 한정특가 상품입니다.',
  },
  {
    id: '2',
    course: {
      id: 'c2',
      name: '클럽72 (오션)',
      location: '인천 중구',
      region: 'SUDOKWON_SOUTH',
      image: 'https://picsum.photos/seed/golf2/800/600',
    },
    date: '2024-12-25',
    time: '12:45',
    price: 210000,
    originalPrice: 280000,
    slotsTotal: 4,
    slotsRemaining: 4,
    type: BookingType.TRANSFER,
    manager: {
      id: 'm2',
      name: '이지혜 매니저',
      rating: 4.8,
      reviewCount: 3400,
      isVerified: true,
    },
    description: '긴급 양도! 바다 보이는 환상의 코스.',
  },
  {
    id: '3',
    course: {
      id: 'c3',
      name: '파주CC',
      location: '경기 파주',
      region: 'SUDOKWON_NORTH',
      image: 'https://picsum.photos/seed/golf3/800/600',
    },
    date: '2024-12-26',
    time: '08:12',
    price: 155000,
    originalPrice: 210000,
    slotsTotal: 4,
    slotsRemaining: 2,
    type: BookingType.JOIN,
    manager: {
      id: 'm3',
      name: '최부장',
      rating: 4.7,
      reviewCount: 890,
      isVerified: false,
    },
    description: '2인 조인 가능합니다. 깔끔한 매너 플레이 원합니다.',
  },
  {
    id: '4',
    course: {
      id: 'c4',
      name: '라데나CC',
      location: '강원 춘천',
      region: 'GANGWON',
      image: 'https://picsum.photos/seed/golf4/800/600',
    },
    date: '2024-12-27',
    time: '06:54',
    price: 120000,
    originalPrice: 180000,
    slotsTotal: 4,
    slotsRemaining: 4,
    type: BookingType.SPECIAL,
    manager: {
      id: 'm4',
      name: '박팀장',
      rating: 4.9,
      reviewCount: 15600,
      isVerified: true,
    },
    description: '강원권 최저가 보장 특가 상품입니다.',
  },
];
